### ISSUE TITLE
Misleading README of @jq-tools/jq 

### ISSUE THREAD

**Issue by markiewiczjakub** [alexxander/jq-tools#2]
Hello,

README of `@jq-tools/jq` package is misleading due to invalid usage of `evaluate` function. In README file we can see:

```ts
import { evaluate, parse } from '@jq-tools/jq';

Array.from(evaluate(parse(`.[] | . * 2`), [1, 2, 3]));
```

But during execution this exact code we end up with error `JqEvaluateError: number "1" is not iterable`. If I run the same code but nesting input into another array the output is valid
```ts
Array.from(evaluate(parse(`.[] | . * 2`), [[1, 2, 3]]));
// output: [2, 4, 6]
```

Output behaviour is strange bacuase it differs from type of input data.

**Object input behaviour**
```ts
Array.from(
    evaluate(parse(`.test`), [
        {
            test: { a: 'a' },
        },
        {
            test: { b: 'b' },
        },
    ])
)
// output: [ { a: 'a' }, { b: 'b' } ]
```
This case acts correctly, because I can address output data using the same index I used in input data.

**Array input behaviour**
```ts
Array.from(
    evaluate(parse(`.[] | . + 1`), [
        [1, 2, 3],
        [11, 12, 13],
    ])
)
// output: [ 2, 3, 4, 12, 13, 14 ]
```
And here evaluation merged input arrays? In my opinion the output should be `[ [ 2, 3, 4 ], [ 12, 13, 14 ] ]`. I think it's a bug. Why? Let's assume that I want to make a function `runJQ` that evaluate only one input like so
```ts
const runJQ = (filter: string, inputValue: object | any[]) => {
	const parsedFilter = parse(filter);
	const evaluation = evaluate(parsedFilter, [inputValue]);

	return Array.from(evaluation)[0];
};

runJQ('.foo', { foo: 'bar' }); // output: bar
runJQ('.[] | . + 1', [1, 2, 3]); // output: 2; expected output: [2, 3, 4]
```

Looking forward for your answer, because I find this package very handy and I will be glad if we can manage to fix it asap.

**Comment by alexxander** [comment]
Hello, thanks for creating this issue.

You are right in the case of the `evaluate` function example from the README file. It should indeed be as follows:
```js
Array.from(evaluate(parse(`.[] | . * 2`), [[1, 2, 3]]));
// output: [2, 4, 6]
```

The outer array plays the role of an iterator of inputs and the inner array is just an array value.

The output from the function is an iterator of values, these are then collected into an array using the `Array.from()` function.

---

As for the third case, I will have to insist that the current behavior is correct:

```js
Array.from(
    evaluate(parse(`.[] | . + 1`), [
        [1, 2, 3],
        [11, 12, 13],
    ])
)
// Output: [2, 3, 4, 12, 13, 14]
```

The snippet above is equivalent to the following `bash` code.

```bash
{ echo "[1,2,3]"; echo "[11,12,13]"; } | jq '.[] | . + 1';

# Alternatively using my lib:
{ echo "[1,2,3]"; echo "[11,12,13]"; } | npx @jq-tools/jq '.[] | . + 1';
```

Output:
```
2
3
4
12
13
14
```

Let me explain what is going on here. Whether it is in the case of the `evaluate` method or one of the bash commands, jq gets two input values `[1,2,3]` and `[11,12,13]`. It then pipes both the values through `.[] | . + 1`.

The left part `.[]` unwraps the arrays producing a stream of three values for both the inputs. `[1,2,3]` changes into three separate values: `1`, `2`, `3`. Each of these values is then piped through `. + 1` which increases the values by one. The result is three distinct values: `2`, `3`, `4`. The same happens with the second input value, the array is unwrapped into three separate values each of which is increased by one. The result is 6 values in total: `2`, `3`, `4`, `12`, `13`, `14`.

You can achieve the behavior you expect by modifying the jq code as follows: `[.[] | . + 1]`. This will additionally wrap the stream of values coming out of jq in an array assuring that there is just a single output for each input.

```bash
{ echo "[1,2,3]"; echo "[11,12,13]"; } | jq '[.[] | . + 1]';
```

Output:
```
[
  2,
  3,
  4
]
[
  12,
  13,
  14
]
```

With the evaluate method it would look as follows:

```js
Array.from(
    evaluate(parse(`.[] | . + 1`), [
        [1, 2, 3],
        [11, 12, 13],
    ])
)
// Output: [[2, 3, 4], [12, 13, 14]]
```

**Comment by markiewiczjakub** [comment]
What a quick response! Thanks!

I appreciate clarification of mechanisms underneath and responding with the solution. It makes sense. That's all I wanted to hear.

Have a great evening :)
